version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: |
          docker build -t demo:$CIRCLE_BRANCH .
          echo "docker build completed"
  test:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: |
          docker run --rm anchore/grype:latest --fail-on critical -o json alpine:latest > scan.json
          echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
