version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: |
          docker build -t company/app:$CIRCLE_BRANCH .
          echo "docker build completed"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
